# Pages CMS Configuration
# Documentation: https://pagescms.org/docs/configuration/

# Media configuration
media: src/assets

# Reusable components
components:
  # Button component
  button:
    type: object
    fields:
      - name: variant
        label: Variant
        type: select
        options:
          values:
            - label: Primary
              value: primary
            - label: Secondary
              value: secondary
        required: true
        default: primary
      - name: size
        label: Size
        type: select
        options:
          values:
            - label: Small
              value: sm
            - label: Medium
              value: md
            - label: Large
              value: lg
        required: true
        default: md
      - name: href
        label: Link URL
        type: string
        required: true
        description: The URL this button links to

  # Card component
  card:
    type: object
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: content
        label: Content
        type: rich-text
        description: Brief description of the card
      - name: image
        label: Image
        type: image
        description: Card image (absolute path, e.g. /src/assets/images/card.jpg)
      - name: button
        label: Button
        component: button

  # Person component
  person:
    type: object
    fields:
      - name: id
        label: ID
        type: string
        required: true
        description: Unique identifier (slug format, e.g. john-doe)
      - name: name
        label: Name
        type: string
        required: true
      - name: headshot
        label: Headshot
        type: image
        required: true
        description: Absolute path from root (e.g. /src/assets/people/john-doe.png)
      - name: title
        label: Job Title
        type: string
        required: true
      - name: sections
        label: Sections
        type: string
        list: true
        description: Department/section tags (e.g. Leadership, Engineering)

  # Partner component
  partner:
    type: object
    fields:
      - name: name
        label: Name
        type: string
        required: true
      - name: affiliation
        label: Affiliation
        type: string
        description: e.g. "Platinum Sponsor"
      - name: url
        label: Website URL
        type: string
        description: Partner's website
      - name: category
        label: Category
        type: string
        required: true
        description: e.g. sponsor, infrastructure, community
      - name: image
        label: Logo
        type: image
        required: true
        description: Absolute path to partner logo (e.g. /src/assets/partners/logo.png)

  # Section components for block variants
  hero_section:
    type: object
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: subtitle
        label: Subtitle
        type: string
      - name: backgroundImage
        label: Background Image
        type: image
        description: Optional hero background image (absolute path, e.g. /src/assets/hero-bg.jpg)

  richtext_section:
    type: object
    fields:
      - name: background
        label: Background Color
        type: select
        options:
          values:
            - label: White
              value: white
            - label: Gray
              value: gray
            - label: Gradient
              value: gradient
        required: true
        default: white
      - name: content
        label: Content
        type: rich-text
        required: true
        description: Markdown content for this section

  card_section:
    type: object
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: rich-text
      - name: cards
        label: Cards
        type: object
        list: true
        component: card
        description: Grid of content cards
      - name: buttons
        label: Action Buttons
        type: object
        list: true
        component: button
        description: Buttons at the bottom of the section

  people_section:
    type: object
    fields:
      - name: category
        label: Category
        type: string
        required: true
        description: Section title (e.g. "Community Leaders")
      - name: people
        label: People
        type: object
        list: true
        component: person
        required: true

  partners_section:
    type: object
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: partners
        label: Partners
        type: object
        list: true
        component: partner
        required: true

# Content collections
content:
  # Pages collection
  - name: pages
    label: Pages
    type: collection
    path: src/content/pages
    format: yaml
    filename: '{fields.permalink}.yaml'
    view:
      fields: [title, description]
      primary: title
    fields:
      - name: title
        label: Page Title
        type: string
        required: true
        description: The title of the page

      - name: permalink
        label: Permalink
        type: string
        description: The slug, without slashes or parents, like 'about-us' or 'omg-3'.
        pattern:
          {
            message: "This must be a web-safe string like 'about-us' or 'omg-3'.",
            regex: '^[a-zA-Z0-9_-]*$',
          }
        required: true

      - name: description
        label: Page Description
        type: rich-text
        description: SEO meta description

      - name: sections
        label: Page Sections
        type: block
        list: true
        required: true
        blockKey: type
        description: Add and arrange page sections in any order
        blocks:
          - name: hero
            label: Hero Section
            component: hero_section

          - name: richText
            label: Rich Text Section
            component: richtext_section

          - name: card
            label: Card Section
            component: card_section

          - name: people
            label: People Section
            component: people_section

          - name: partners
            label: Partners Section
            component: partners_section

  # People collection
  - name: people
    label: People
    type: collection
    path: src/content/people
    extension: json
    filename: '{{fields.id}}'
    view:
      fields: [name, title]
      primary: name
    fields:
      - name: id
        label: ID
        type: string
        required: true
        description: Unique identifier (slug format, e.g. john-doe)

      - name: name
        label: Name
        type: string
        required: true

      - name: headshot
        label: Headshot
        type: image
        required: true
        description: Absolute path from root (e.g. /src/assets/people/john-doe.png)

      - name: title
        label: Job Title
        type: string
        required: true

      - name: sections
        label: Sections/Departments
        type: string
        list: true
        description: Tags like "Leadership", "Engineering", etc.

  # Site configuration (singleton)
  - name: site-config
    label: Site Settings
    type: file
    path: src/content/site/config.json
    fields:
      - name: title
        label: Site Title
        type: string
        required: true
        description: The name of your website

      - name: description
        label: Site Description
        type: string
        required: true
        description: Default meta description for SEO

      - name: url
        label: Site URL
        type: string
        required: true
        description: Your website's URL (e.g. https://example.com)

      - name: favicon
        label: Favicon Path
        type: string
        default: /favicon.svg
        description: Path to your favicon file

      - name: defaultOgImage
        label: Default Open Graph Image
        type: image
        description: Default image for social media sharing

      - name: social
        label: Social Media Links
        type: object
        fields:
          - name: bluesky
            label: BlueSky URL
            type: string
            description: Full URL to your Bluesky profile
          - name: mastodon
            label: Mastodon URL
            type: string
            description: Full URL to your Mastodon profile

          - name: github
            label: GitHub URL
            type: string
            description: Full URL to your GitHub profile or organization

          - name: linkedin
            label: LinkedIn URL
            type: string
            description: Full URL to your LinkedIn profile or company page

          - name: x
            label: X URL
            type: string
            description: Full URL to your X profile

          - name: facebook
            label: Facebook URL
            type: string
            description: Full URL to your Facebook page

          - name: instagram
            label: Instagram URL
            type: string
            description: Full URL to your Instagram profile

          - name: youtube
            label: YouTube URL
            type: string
            description: Full URL to your YouTube channel

  # Navigation menus
  - name: navigation
    label: Navigation Menus
    type: collection
    path: src/content/navigation
    extension: json
    filename: '{{fields.slug}}'
    view:
      fields: [title]
      primary: title
    fields:
      - name: slug
        label: Menu ID
        type: string
        required: true
        description: Unique identifier for this menu (e.g. main, footer-1, footer-2)
        pattern:
          {
            message: "Must be a web-safe string like 'main' or 'footer-1'.",
            regex: '^[a-zA-Z0-9_-]*$',
          }

      - name: title
        label: Menu Title
        type: string
        required: true
        description: Display title for this menu

      - name: items
        label: Menu Items
        type: object
        list: true
        required: true
        fields:
          - name: label
            label: Link Label
            type: string
            required: true
            description: Text displayed for the link

          - name: href
            label: URL
            type: string
            required: true
            description: Link destination (e.g. / or /about)

          - name: description
            label: Description
            type: string
            description: Optional description for accessibility
